#!/usr/bin/env python3

""" 
wcc: wc re-written in Python
Author: Shiyan Shirani
Date: 20th September 2023
"""
import os
import sys
import locale


def run(path, identifier=None, all=False):
    try:
        table = {
            "-w": word_count,
            "-c": byte_count,
            "-m": character_count,
            "-l": line_count,
        }
        if all:
            print(
                table["-c"](path),
                table["-l"](path),
                table["-w"](path),
                path.split('/')[-1]
            )
        else:
            result = table[identifier](path)
            print(result, path.split('/')[-1])

    except FileNotFoundError:
        print("error: file path incorrect.")
    except Exception as error:
        print("error:", error)


def word_count(path):
    with open(path, "r") as file:
        content = file.read()
        return len(content.split())

def line_count(path):
    with open(path, "r") as file:
        lines = file.readlines()
        return len(lines)

def byte_count(path):
    return os.path.getsize(path)

def character_count(path):
    with open(path, "r", encoding='utf-8') as file:
        content = file.read()
        return len(content)

def get_absolute_path(path):
    abs_path = os.path.abspath(path)
    return abs_path

def get_file_name(path):
    return os.path.basename(path)



if __name__ == "__main__":
    try:
        if len(sys.argv) < 1:
            print("error: file path not provided.")

        if len(sys.argv) == 2:
            path = get_absolute_path(sys.argv[1])
            run(path, all=True)
        else:
            path = get_absolute_path(sys.argv[2])
            flag = sys.argv[1]
            run(path, flag)
    except Exception as err:
        print(err)
